{%- if DRYDOCK_ENABLE_RESOURCE_MANAGEMENT -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  template:
    spec:
      containers:
        - name: lms
          resources:
            limits:
              cpu: "{{ DRYDOCK_LMS_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_LMS_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_LMS_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_LMS_REQUEST_MEMORY }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  template:
    spec:
      containers:
        - name: cms
          resources:
            limits:
              cpu: "{{ DRYDOCK_CMS_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_CMS_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_CMS_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_CMS_REQUEST_MEMORY }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-worker
spec:
  template:
    spec:
      containers:
        - name: lms-worker
          resources:
            limits:
              cpu: "{{ DRYDOCK_LMS_WORKER_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_LMS_WORKER_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_LMS_WORKER_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_LMS_WORKER_REQUEST_MEMORY }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
spec:
  template:
    spec:
      containers:
        - name: cms-worker
          resources:
            limits:
              cpu: "{{ DRYDOCK_CMS_WORKER_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_CMS_WORKER_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_CMS_WORKER_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_CMS_WORKER_REQUEST_MEMORY }}"
{%- if FORUM_DOCKER_IMAGE is defined %}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
spec:
  template:
    spec:
      containers:
        - name: forum
          resources:
            limits:
              cpu: "{{ DRYDOCK_FORUM_LIMIT_CPU }}"
              memory: "{{ DRYDOCK_FORUM_LIMIT_MEMORY }}"
            requests:
              cpu: "{{ DRYDOCK_FORUM_REQUEST_CPU }}"
              memory: "{{ DRYDOCK_FORUM_REQUEST_MEMORY }}"
{% endif -%}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lms
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cms
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: forum
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lms-worker
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cms-worker
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
{% endif -%}
{%- if DRYDOCK_NEWRELIC -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  template:
    spec:
      containers:
        - name: lms
          args:
            - |
              newrelic-admin run-program uwsgi \
              --static-map /static=/openedx/staticfiles/ \
              --static-map /media=/openedx/media/ \
              --http 0.0.0.0:8000 --thunder-lock \
              --single-interpreter --enable-threads \
              --processes=${UWSGI_WORKERS:-2} \
              --buffer-size=8192 \
              --wsgi-file $SERVICE_VARIANT/wsgi.py
          command: ["/bin/bash", "-c"]
          env:
          - name: NEW_RELIC_CONFIG_FILE
            value: /openedx/newrelic/newrelic.ini
          volumeMounts:
          - mountPath: /openedx/newrelic/
            name: newrelic-ini
      volumes:
      - configMap:
          name: newrelic-cm
        name: newrelic-ini
---
{% endif -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-worker
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-worker
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
{% if DRYDOCK_INIT_JOBS %}
apiVersion: batch/v1
kind: Job
metadata:
  name: cms-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: lms-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-job
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
{%- if FORUM_DOCKER_IMAGE is defined %}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: forum-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
{%- endif %}
{%- if MINIO_DOCKER_IMAGE is defined %}
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-job
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
{%- endif %}
{%- if NOTES_DOCKER_IMAGE is defined %}
apiVersion: batch/v1
kind: Job
metadata:
  name: notes-job-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: notes-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: notes-job-lms
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
---
{%- endif %}
{% endif -%}
{{ patch("drydock-overrides") }}
