apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 38.0.2
  releaseName: prometheus
  includeCRDs: true
{%- if DRYDOCK_PROMETHEUS_VALUES|default(false) %}
  valuesInline:
    {{ DRYDOCK_PROMETHEUS_VALUES | indent(4) }}
{%- endif %}

{%- if DRYDOCK_PROMETHEUS_OVERLAYS|default(false) %}
patches: {{ DRYDOCK_PROMETHEUS_OVERLAYS }}
{%- endif %}
