apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 38.0.2
  releaseName: prometheus
  includeCRDs: true
  valuesInline: {{ DRYDOCK_PROMETHEUS_VALUES }}

{% if DRYDOCK_PROMETHEUS_PATCHES|default(false) -%}
patches:
{{ DRYDOCK_PROMETHEUS_OVERLAYS }}
{% endif -%}
