apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-debug
  namespace: {{ K8S_NAMESPACE }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    {% if DRYDOCK_DEBUG_BY_COOKIE -%}
    nginx.ingress.kubernetes.io/canary-by-cookie: {{ OPENEDX_DEBUG_COOKIE }}
    {% elif DRYDOCK_DEBUG_BY_HEADER -%}
    nginx.ingress.kubernetes.io/canary-by-header: {{ DRYDOCK_DEBUG_HEADER }}
    nginx.ingress.kubernetes.io/canary-by-header-value: {{ DRYDOCK_DEBUG_HEADER_VALUE }}
    {%- endif %}
    {%- if DRYDOCK_AUTO_TLS and not DRYDOCK_CUSTOM_CERTS%}
    cert-manager.io/issuer: letsencrypt
    {%- endif %}
    argocd.argoproj.io/sync-wave: "5"
spec:
  rules:
    {%- for host, prefix in [(LMS_HOST, "lms"), (CMS_HOST, "cms")] %}
  - host: {{ host }}
    http:
      paths:
      - backend:
          service:
            name: {{prefix}}-debug
            port:
              number: 8000
        path: /
        pathType: Prefix
    {%- endfor %}
  {% if DRYDOCK_AUTO_TLS -%}
  tls:
  - hosts:
    {%- for host in [LMS_HOST, CMS_HOST] %}
    - {{ host }}
    {%- endfor %}
    secretName: {{ K8S_NAMESPACE }}-tls
  {%- endif %}
