{% if ENABLE_WEB_PROXY %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: caddy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{% endif %}
{% if RUN_ELASTICSEARCH %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{% endif %}
{% if RUN_MONGODB %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{% endif %}
{% if RUN_MYSQL %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{% endif %}
{% if RUN_REDIS %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{% endif %}

{% if DRYDOCK_ENABLE_NFS %}
{% if RUN_ELASTICSEARCH %}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch
  labels:
    target-service: elasticsearch
spec:
  nfs:
    path: /mnt/elasticsearch
    server: {{ NFS_SERVER }}
  persistentVolumeReclaimPolicy: Retain
{% endif -%}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openedx-data
  labels:
    target-service: openedx-data
spec:
  nfs:
    path: /edx/var/edxapp/shared-data/openedx-data
    server: {{ NFS_SERVER }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openedx-data
spec:
  selector:
    matchLabels:
      target-service: openedx-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openedx-media
  labels:
    target-service: openedx-media
spec:
  nfs:
    path: /edx/var/edxapp/shared-data/openedx-media
    server: {{ NFS_SERVER }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openedx-media
spec:
  selector:
    matchLabels:
      target-service: openedx-media
{% endif -%}

{{ patch("k8s-volumes") }}