{%- if FORUM_DOCKER_IMAGE is defined %}
apiVersion: batch/v1
kind: Job
metadata:
  name: forum-job
  labels:
    app.kubernetes.io/component: job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: forum
        image: {{ FORUM_DOCKER_IMAGE }}
        args:
          - sh
          - -e
          - -c
          - 'bundle exec rake search:initialize
            bundle exec rake search:rebuild_index'
        env:
          - name: SEARCH_SERVER
            value: "{{ ELASTICSEARCH_SCHEME }}://{{ ELASTICSEARCH_HOST }}:{{ ELASTICSEARCH_PORT }}"
          - name: MONGODB_AUTH
            value: "{% if MONGODB_USERNAME and MONGODB_PASSWORD %}{{ MONGODB_USERNAME}}:{{ MONGODB_PASSWORD }}@{% endif %}"
          - name: MONGODB_HOST
            value: "{{ MONGODB_HOST }}"
          - name: MONGODB_PORT
            value: "{{ MONGODB_PORT }}"
          - name: MONGODB_DATABASE
            value: "{{ FORUM_MONGODB_DATABASE }}"
          - name: MONGOHQ_URL
            value: "mongodb://$(MONGODB_AUTH)$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DATABASE)"
          - name: SEARCH_SERVER_ES7
            value: "$(SEARCH_SERVER)"
          - name: MONGOID_AUTH_MECH
            value: ":scram"
{%- endif %}
