apiVersion: batch/v1
kind: Job
metadata:
  name: forum-job
  labels:
    app.kubernetes.io/component: job
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: forum
        image: {{ FORUM_DOCKER_IMAGE }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          bundle exec rake search:initialize
          bundle exec rake search:rebuild_indices
        env:
          - name: SEARCH_SERVER
            value: "{{ ELASTICSEARCH_SCHEME }}://{{ ELASTICSEARCH_HOST }}:{{ ELASTICSEARCH_PORT }}"
          - name: MONGODB_AUTH
            value: "{% if MONGODB_USERNAME and MONGODB_PASSWORD %}{{ MONGODB_USERNAME}}:{{ MONGODB_PASSWORD }}@{% endif %}"
          - name: MONGODB_HOST
            value: "{{ MONGODB_HOST }}"
          - name: MONGODB_PORT
            value: "{{ MONGODB_PORT }}"
          - name: MONGODB_DATABASE
            value: "{{ FORUM_MONGODB_DATABASE }}"
